-- openplace backend (Rust) — initial PostgreSQL schema.
-- Port of prisma/schema.prisma (MySQL) with PG-native improvements:
--   * UNIQUE NULLS NOT DISTINCT replaces the MySQL "<=>" NULL-safe hacks
--   * timestamptz everywhere, bytea for blobs
-- Table/column names are snake_case.

CREATE TABLE alliances (
    id             int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name           text NOT NULL UNIQUE,
    description    text,
    hq_latitude    double precision,
    hq_longitude   double precision,
    pixels_painted int  NOT NULL DEFAULT 0,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX alliances_pixels_painted_idx ON alliances (pixels_painted);

CREATE TABLE users (
    id                        int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name                      text NOT NULL,
    registration_ip           text,
    last_ip                   text,
    discord                   text,
    discord_user_id           text UNIQUE,
    nickname                  text,
    country                   text NOT NULL DEFAULT 'US',
    email                     text UNIQUE,
    password_hash             text NOT NULL,
    banned                    boolean NOT NULL DEFAULT false,
    verified                  boolean NOT NULL DEFAULT false,
    suspension_reason         text,
    timeout_until             timestamptz NOT NULL DEFAULT now(),
    needs_phone_verification  boolean NOT NULL DEFAULT false,
    is_customer               boolean NOT NULL DEFAULT false,
    role                      text NOT NULL DEFAULT 'user',
    pixels_painted            int NOT NULL DEFAULT 0,
    droplets                  int NOT NULL DEFAULT 0,
    max_charges               double precision NOT NULL DEFAULT 20,
    current_charges           double precision NOT NULL DEFAULT 20,
    charges_cooldown_ms       int NOT NULL DEFAULT 30000,
    charges_last_updated_at   timestamptz NOT NULL DEFAULT now(),
    extra_colors_bitmap       int NOT NULL DEFAULT 0,
    flags_bitmap              bytea,
    equipped_flag             int NOT NULL DEFAULT 0,
    show_last_pixel           boolean NOT NULL DEFAULT true,
    picture                   text,
    level                     double precision NOT NULL DEFAULT 1,
    alliance_id               int REFERENCES alliances(id) ON DELETE SET NULL,
    alliance_role             text NOT NULL DEFAULT 'member',
    alliance_joined_at        timestamptz,
    created_at                timestamptz NOT NULL DEFAULT now(),
    updated_at                timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX users_banned_idx ON users (banned);
CREATE INDEX users_registration_ip_idx ON users (registration_ip);
CREATE INDEX users_last_ip_idx ON users (last_ip);
CREATE INDEX users_role_pixels_painted_idx ON users (role, pixels_painted);
CREATE INDEX users_pixels_painted_idx ON users (pixels_painted);

CREATE TABLE alliance_banned_users (
    id          int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id     int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    alliance_id int NOT NULL REFERENCES alliances(id) ON DELETE CASCADE,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX alliance_banned_users_user_alliance_uq
    ON alliance_banned_users (user_id, alliance_id);

CREATE TABLE alliance_invites (
    id          uuid PRIMARY KEY,
    alliance_id int NOT NULL REFERENCES alliances(id) ON DELETE CASCADE,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX alliance_invites_alliance_idx ON alliance_invites (alliance_id);

CREATE TABLE favorite_locations (
    id         int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name       text NOT NULL DEFAULT '',
    latitude   double precision NOT NULL,
    longitude  double precision NOT NULL
);
CREATE INDEX favorite_locations_user_idx ON favorite_locations (user_id);

CREATE TABLE banned_ips (
    id                int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cidr              text NOT NULL,
    ipv4_min          bigint,
    ipv4_max          bigint,
    ipv6_min          bytea,
    ipv6_max          bytea,
    suspension_reason text NOT NULL,
    user_id           int REFERENCES users(id) ON DELETE CASCADE,
    created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX banned_ips_cidr_idx ON banned_ips (cidr);
CREATE INDEX banned_ips_v4_idx ON banned_ips (ipv4_min, ipv4_max);
CREATE INDEX banned_ips_v6_idx ON banned_ips (ipv6_min, ipv6_max);
CREATE INDEX banned_ips_user_idx ON banned_ips (user_id);

CREATE TABLE regions (
    id          int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    city_id     int NOT NULL UNIQUE,
    name        text NOT NULL,
    number      int NOT NULL DEFAULT 1,
    country_id  int NOT NULL,
    latitude    double precision NOT NULL,
    longitude   double precision NOT NULL,
    population  bigint NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX regions_lat_lon_uq ON regions (latitude, longitude);
CREATE INDEX regions_lat_idx ON regions (latitude);
CREATE INDEX regions_lon_idx ON regions (longitude);
CREATE INDEX regions_population_idx ON regions (population);
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX regions_name_trgm_idx ON regions USING gin (name gin_trgm_ops);

CREATE TABLE tiles (
    id         bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    season     smallint NOT NULL DEFAULT 0,
    x          int NOT NULL,
    y          int NOT NULL,
    image_data bytea,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX tiles_season_xy_uq ON tiles (season, x, y);

CREATE TABLE pixels (
    id                bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    season            smallint NOT NULL DEFAULT 0,
    tile_x            int NOT NULL,
    tile_y            int NOT NULL,
    x                 smallint NOT NULL,
    y                 smallint NOT NULL,
    color_id          smallint NOT NULL,
    painted_by        int NOT NULL REFERENCES users(id),
    region_city_id    int,
    region_country_id int,
    painted_at        timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (season, tile_x, tile_y) REFERENCES tiles (season, x, y)
);
CREATE UNIQUE INDEX pixels_pos_uq ON pixels (season, tile_x, tile_y, x, y);
CREATE INDEX pixels_tile_idx ON pixels (season, tile_x, tile_y);
CREATE INDEX pixels_painted_by_idx ON pixels (painted_by, painted_at);

CREATE TABLE profile_pictures (
    id    int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url   text NOT NULL,
    user_id int NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE sessions (
    id         uuid PRIMARY KEY,
    user_id    int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX sessions_user_idx ON sessions (user_id);

CREATE TABLE password_reset_tokens (
    id         uuid PRIMARY KEY,
    user_id    int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX password_reset_tokens_user_idx ON password_reset_tokens (user_id);

CREATE TABLE tickets (
    id                uuid PRIMARY KEY,
    user_id           int REFERENCES users(id) ON DELETE SET NULL,
    reported_user_id  int REFERENCES users(id) ON DELETE SET NULL,
    moderator_user_id int REFERENCES users(id) ON DELETE SET NULL,
    latitude          double precision NOT NULL,
    longitude         double precision NOT NULL,
    zoom              double precision NOT NULL,
    reason            text NOT NULL,
    notes             text NOT NULL,
    image             bytea,
    resolution        text,
    severe            boolean NOT NULL DEFAULT false,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX tickets_resolution_idx ON tickets (resolution, created_at);
CREATE INDEX tickets_reported_idx ON tickets (reported_user_id);
CREATE INDEX tickets_author_idx ON tickets (user_id);
CREATE INDEX tickets_moderator_idx ON tickets (moderator_user_id);

CREATE TABLE user_notes (
    id               int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id          int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reported_user_id int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content          text NOT NULL,
    created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX user_notes_reported_idx ON user_notes (reported_user_id, created_at);

CREATE TABLE leaderboard_view (
    id             int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type           text NOT NULL,
    mode           text NOT NULL,
    entity_id      int,
    region_id      int,
    rank           int NOT NULL,
    pixels_painted int NOT NULL,
    last_updated   timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX leaderboard_view_uq ON leaderboard_view (type, mode, entity_id, region_id) NULLS NOT DISTINCT;
CREATE INDEX leaderboard_view_rank_idx ON leaderboard_view (type, mode, rank);
CREATE INDEX leaderboard_view_region_idx ON leaderboard_view (type, mode, region_id);

CREATE TABLE user_region_stats (
    id                bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id           int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    region_city_id    int,
    region_country_id int,
    alliance_id       int,
    time_period       timestamptz NOT NULL,
    pixels_painted    int NOT NULL DEFAULT 0,
    last_painted_at   timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX user_region_stats_uq ON user_region_stats
    (user_id, region_city_id, region_country_id, alliance_id, time_period) NULLS NOT DISTINCT;
CREATE INDEX user_region_stats_city_user_idx ON user_region_stats (region_city_id, user_id);
CREATE INDEX user_region_stats_city_alliance_idx ON user_region_stats (region_city_id, alliance_id);
CREATE INDEX user_region_stats_city_user_painted_idx ON user_region_stats (region_city_id, last_painted_at, pixels_painted, user_id);

CREATE TABLE user_region_stats_daily (
    id                bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id           int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    region_city_id    int,
    region_country_id int,
    alliance_id       int,
    date              timestamptz NOT NULL,
    pixels_painted    int NOT NULL DEFAULT 0,
    last_painted_at   timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX user_region_stats_daily_uq ON user_region_stats_daily
    (user_id, region_city_id, region_country_id, alliance_id, date) NULLS NOT DISTINCT;
CREATE INDEX user_region_stats_daily_city_date_idx ON user_region_stats_daily (region_city_id, date, pixels_painted, user_id);
CREATE INDEX user_region_stats_daily_city_date_alliance_idx ON user_region_stats_daily (region_city_id, date, pixels_painted, alliance_id);
CREATE INDEX user_region_stats_daily_country_date_idx ON user_region_stats_daily (region_country_id, date, pixels_painted);

CREATE TABLE notifications (
    id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id         int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    sending_user_id int NOT NULL DEFAULT -1 REFERENCES users(id),
    read            boolean NOT NULL DEFAULT false,
    icon            text NOT NULL,
    title           text NOT NULL,
    message         text NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX notifications_user_read_idx ON notifications (user_id, read, created_at);
CREATE INDEX notifications_user_created_idx ON notifications (user_id, created_at);

CREATE TABLE system_notifications (
    id         int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    icon       text NOT NULL,
    title      text NOT NULL,
    message    text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX system_notifications_created_idx ON system_notifications (created_at);

CREATE TABLE system_notification_reads (
    id                     int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    system_notification_id int NOT NULL REFERENCES system_notifications(id) ON DELETE CASCADE,
    user_id                int NOT NULL,
    read_at                timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX system_notification_reads_uq ON system_notification_reads (system_notification_id, user_id);
CREATE INDEX system_notification_reads_user_idx ON system_notification_reads (user_id);
